version: '3'

services:
  poker-hand-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: poker-hand-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
